/*
 * TableTest.java
 *
 * Created on 3. Juni 2003, 09:58
 *
 * The MIT License
 *
 * Copyright (C) 2003 
 * Tilmann Kuhn           Gildestr. 34
 * http://www.tkuhn.de    76149 Karlsruhe
 * swingutils@tkuhn.de    Germany
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package de.tkuhn.swing;

import javax.swing.JFrame;

/**
 * Demo file just used to build a JFrame with a TablePanel in it
 * 
 * @author Tilmann Kuhn
 */
public class TableActionDemo extends JFrame {

	private static final long serialVersionUID = 1L;

	/** Creates new form TableTest */
	public TableActionDemo() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		tablePanel1 = new de.tkuhn.swing.TableActionPanel();

		getContentPane().setLayout(
				new javax.swing.BoxLayout(getContentPane(),
						javax.swing.BoxLayout.X_AXIS));

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});

		tablePanel1.setFont(new java.awt.Font("Dialog", 0, 11));
		tablePanel1.setMinimumSize(new java.awt.Dimension(213, 52));
		tablePanel1.setPreferredSize(new java.awt.Dimension(453, 433));
		getContentPane().add(tablePanel1);

		pack();
	}// GEN-END:initComponents

	/** Exit the Application */
	void exitForm(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_exitForm
		System.exit(0);
	}// GEN-LAST:event_exitForm

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		new TableActionDemo().setVisible(true);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private de.tkuhn.swing.TableActionPanel tablePanel1;
	// End of variables declaration//GEN-END:variables

}
